"""notifications + dashboards

Revision ID: 143f1fdeb609
Revises: 69c5bacbc32d
Create Date: 2026-05-26 09:27:18.492179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '143f1fdeb609'
down_revision: Union[str, Sequence[str], None] = '69c5bacbc32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_def',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_dashboard_def_key')
    )
    op.create_index(op.f('ix_dashboard_def_tenant_id'), 'dashboard_def', ['tenant_id'], unique=False)
    op.create_table('notification_def',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('gxl_condition', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_notification_def_key')
    )
    op.create_index(op.f('ix_notification_def_tenant_id'), 'notification_def', ['tenant_id'], unique=False)
    op.create_table('widget_def',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_def_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_def_id'], ['dashboard_def.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_def_id', 'key', name='uq_widget_def_key')
    )
    op.create_index(op.f('ix_widget_def_dashboard_def_id'), 'widget_def', ['dashboard_def_id'], unique=False)
    op.create_index(op.f('ix_widget_def_tenant_id'), 'widget_def', ['tenant_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('def_key', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('entity_key', sa.String(length=80), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_record_id'), 'notification', ['record_id'], unique=False)
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)
    op.create_index('ix_notification_user_read', 'notification', ['user_id', 'read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_user_read', table_name='notification')
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_record_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_widget_def_tenant_id'), table_name='widget_def')
    op.drop_index(op.f('ix_widget_def_dashboard_def_id'), table_name='widget_def')
    op.drop_table('widget_def')
    op.drop_index(op.f('ix_notification_def_tenant_id'), table_name='notification_def')
    op.drop_table('notification_def')
    op.drop_index(op.f('ix_dashboard_def_tenant_id'), table_name='dashboard_def')
    op.drop_table('dashboard_def')
    # ### end Alembic commands ###
