"""party + account tables (17a stage 1) + nullable account_id

Revision ID: 3aaf9ce9edeb
Revises: d2a4f9ad44dd
Create Date: 2026-05-26 20:29:41.993047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaf9ce9edeb'
down_revision: Union[str, Sequence[str], None] = 'd2a4f9ad44dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_node_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_party_id', sa.UUID(), nullable=True),
    sa.Column('customer_record_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['owner_node_id'], ['org_node.id'], ),
    sa.ForeignKeyConstraint(['parent_party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_customer_record_id'), 'party', ['customer_record_id'], unique=False)
    op.create_index(op.f('ix_party_parent_party_id'), 'party', ['parent_party_id'], unique=False)
    op.create_index(op.f('ix_party_tenant_id'), 'party', ['tenant_id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_node_id', sa.UUID(), nullable=True),
    sa.Column('holder_party_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('credit_terms', sa.String(length=80), nullable=True),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holder_party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['owner_node_id'], ['org_node.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_holder_party_id'), 'account', ['holder_party_id'], unique=False)
    op.create_index(op.f('ix_account_parent_account_id'), 'account', ['parent_account_id'], unique=False)
    op.create_index(op.f('ix_account_tenant_id'), 'account', ['tenant_id'], unique=False)
    op.add_column('invoice', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoice_account_id'), 'invoice', ['account_id'], unique=False)
    op.create_foreign_key(None, 'invoice', 'account', ['account_id'], ['id'])
    op.add_column('order', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_order_account_id'), 'order', ['account_id'], unique=False)
    op.create_foreign_key(None, 'order', 'account', ['account_id'], ['id'])
    op.add_column('service', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_service_account_id'), 'service', ['account_id'], unique=False)
    op.create_foreign_key(None, 'service', 'account', ['account_id'], ['id'])
    op.add_column('subscription', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_subscription_account_id'), 'subscription', ['account_id'], unique=False)
    op.create_foreign_key(None, 'subscription', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###
    # (removed autogenerate's spurious drops of the E13 raw-SQL perf indexes ix_event_tenant_created /
    #  ix_record_tenant_entity_created — they are not model-declared, must survive.)

    # RLS: party + account are ordinary tenant-scoped tables (16a isolation list) — standard policy.
    for tbl in ("party", "account"):
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {tbl}
              USING (tenant_id = NULLIF(current_setting('gaahex.tenant_id', true), '')::uuid)
              WITH CHECK (tenant_id = NULLIF(current_setting('gaahex.tenant_id', true), '')::uuid);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON account;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON party;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_account_id'), table_name='subscription')
    op.drop_column('subscription', 'account_id')
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_index(op.f('ix_service_account_id'), table_name='service')
    op.drop_column('service', 'account_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_account_id'), table_name='order')
    op.drop_column('order', 'account_id')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_account_id'), table_name='invoice')
    op.drop_column('invoice', 'account_id')
    op.drop_index(op.f('ix_account_tenant_id'), table_name='account')
    op.drop_index(op.f('ix_account_parent_account_id'), table_name='account')
    op.drop_index(op.f('ix_account_holder_party_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_party_tenant_id'), table_name='party')
    op.drop_index(op.f('ix_party_parent_party_id'), table_name='party')
    op.drop_index(op.f('ix_party_customer_record_id'), table_name='party')
    op.drop_table('party')
    # ### end Alembic commands ###
