"""saved_view + pending_approval

Revision ID: 510b90a677be
Revises: 9e0d19317944
Create Date: 2026-05-26 10:30:54.432808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '510b90a677be'
down_revision: Union[str, Sequence[str], None] = '9e0d19317944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_key', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=60), nullable=True),
    sa.Column('to_status', sa.String(length=60), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_approval_entity_key'), 'pending_approval', ['entity_key'], unique=False)
    op.create_index(op.f('ix_pending_approval_record_id'), 'pending_approval', ['record_id'], unique=False)
    op.create_index(op.f('ix_pending_approval_tenant_id'), 'pending_approval', ['tenant_id'], unique=False)
    op.create_table('saved_view_def',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_view_def_tenant_entity', 'saved_view_def', ['tenant_id', 'entity_key'], unique=False)
    op.create_index(op.f('ix_saved_view_def_tenant_id'), 'saved_view_def', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_view_def_tenant_id'), table_name='saved_view_def')
    op.drop_index('ix_saved_view_def_tenant_entity', table_name='saved_view_def')
    op.drop_table('saved_view_def')
    op.drop_index(op.f('ix_pending_approval_tenant_id'), table_name='pending_approval')
    op.drop_index(op.f('ix_pending_approval_record_id'), table_name='pending_approval')
    op.drop_index(op.f('ix_pending_approval_entity_key'), table_name='pending_approval')
    op.drop_table('pending_approval')
    # ### end Alembic commands ###
