"""ipam + usage tables

Revision ID: 5dbf421773ca
Revises: 6e5dbe4b40a8
Create Date: 2026-05-26 17:55:10.543414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dbf421773ca'
down_revision: Union[str, Sequence[str], None] = '6e5dbe4b40a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_pool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_node_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_node_id'], ['org_node.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_pool_tenant_id'), 'resource_pool', ['tenant_id'], unique=False)
    op.create_table('usage_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_node_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_rate', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['owner_node_id'], ['org_node.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_record_invoice_id'), 'usage_record', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_usage_record_subscription_id'), 'usage_record', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_record_tenant_id'), 'usage_record', ['tenant_id'], unique=False)
    op.create_table('pool_allocation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['resource_pool.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_allocation_pool_id'), 'pool_allocation', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_allocation_service_id'), 'pool_allocation', ['service_id'], unique=False)
    op.create_index(op.f('ix_pool_allocation_tenant_id'), 'pool_allocation', ['tenant_id'], unique=False)
    op.create_index('uq_pool_alloc_active', 'pool_allocation', ['pool_id', 'value'], unique=True, postgresql_where=sa.text("status = 'ALLOCATED'"))
    # ### end Alembic commands ###
    # (removed autogenerate's spurious drops of the E13 perf indexes — they must survive.)

    for table in ("resource_pool", "pool_allocation", "usage_record"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid)
              WITH CHECK (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("resource_pool", "pool_allocation", "usage_record"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pool_alloc_active', table_name='pool_allocation', postgresql_where=sa.text("status = 'ALLOCATED'"))
    op.drop_index(op.f('ix_pool_allocation_tenant_id'), table_name='pool_allocation')
    op.drop_index(op.f('ix_pool_allocation_service_id'), table_name='pool_allocation')
    op.drop_index(op.f('ix_pool_allocation_pool_id'), table_name='pool_allocation')
    op.drop_table('pool_allocation')
    op.drop_index(op.f('ix_usage_record_tenant_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_subscription_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_invoice_id'), table_name='usage_record')
    op.drop_table('usage_record')
    op.drop_index(op.f('ix_resource_pool_tenant_id'), table_name='resource_pool')
    op.drop_table('resource_pool')
    # ### end Alembic commands ###
