"""notification depth (category, priority, prefs)

Revision ID: 61f6b7aa6a55
Revises: 3a9203795d07
Create Date: 2026-05-26 11:11:00.619005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f6b7aa6a55'
down_revision: Union[str, Sequence[str], None] = '3a9203795d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_pref',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'category', 'channel', name='uq_notification_pref')
    )
    op.create_index(op.f('ix_notification_pref_tenant_id'), 'notification_pref', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_pref_user_id'), 'notification_pref', ['user_id'], unique=False)
    op.add_column('notification', sa.Column('category', sa.String(length=40), server_default='system', nullable=False))
    op.add_column('notification', sa.Column('priority', sa.String(length=20), server_default='info', nullable=False))
    op.add_column('notification_def', sa.Column('category', sa.String(length=40), server_default='system', nullable=False))
    op.add_column('notification_def', sa.Column('priority', sa.String(length=20), server_default='info', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_def', 'priority')
    op.drop_column('notification_def', 'category')
    op.drop_column('notification', 'priority')
    op.drop_column('notification', 'category')
    op.drop_index(op.f('ix_notification_pref_user_id'), table_name='notification_pref')
    op.drop_index(op.f('ix_notification_pref_tenant_id'), table_name='notification_pref')
    op.drop_table('notification_pref')
    # ### end Alembic commands ###
