"""events

Revision ID: 69c5bacbc32d
Revises: f58c3c204483
Create Date: 2026-05-26 07:30:03.477277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69c5bacbc32d'
down_revision: Union[str, Sequence[str], None] = 'f58c3c204483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('entity_key', sa.String(length=80), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_record_id'), 'event', ['record_id'], unique=False)
    op.create_index(op.f('ix_event_tenant_id'), 'event', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_tenant_id'), table_name='event')
    op.drop_index(op.f('ix_event_record_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
