"""service + interaction tables

Revision ID: 6e5dbe4b40a8
Revises: 7f342faffc15
Create Date: 2026-05-26 17:11:49.216808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5dbe4b40a8'
down_revision: Union[str, Sequence[str], None] = '7f342faffc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_node_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('agent_user_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['owner_node_id'], ['org_node.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_customer_id'), 'interaction', ['customer_id'], unique=False)
    op.create_index(op.f('ix_interaction_tenant_id'), 'interaction', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_interaction_ticket_id'), 'interaction', ['ticket_id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_node_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['owner_node_id'], ['org_node.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_customer_id'), 'service', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_subscription_id'), 'service', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_service_tenant_id'), 'service', ['tenant_id'], unique=False)
    op.create_table('service_resource',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_resource_service_id'), 'service_resource', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_resource_tenant_id'), 'service_resource', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate wanted to DROP the E13 perf indexes (ix_event_tenant_created /
    # ix_record_tenant_entity_created) because they were added by raw SQL (not model index=True).
    # Those drops were removed so the indexes SURVIVE.

    for table in ("service", "service_resource", "interaction"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid)
              WITH CHECK (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("service", "service_resource", "interaction"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_resource_tenant_id'), table_name='service_resource')
    op.drop_index(op.f('ix_service_resource_service_id'), table_name='service_resource')
    op.drop_table('service_resource')
    op.drop_index(op.f('ix_service_tenant_id'), table_name='service')
    op.drop_index(op.f('ix_service_subscription_id'), table_name='service')
    op.drop_index(op.f('ix_service_customer_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_interaction_ticket_id'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_tenant_id'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_customer_id'), table_name='interaction')
    op.drop_table('interaction')
    # ### end Alembic commands ###
