"""product catalog + report_def + sub.product_id + line.kind

Revision ID: 71c6d6acef90
Revises: 618f5b791c26
Create Date: 2026-05-26 15:13:12.564350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71c6d6acef90'
down_revision: Union[str, Sequence[str], None] = '618f5b791c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_amount', sa.BigInteger(), nullable=False),
    sa.Column('cycle', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_product_key')
    )
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_table('report_def',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'owner_user_id', 'key', name='uq_report_def_key')
    )
    op.create_index(op.f('ix_report_def_owner_user_id'), 'report_def', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_report_def_tenant_id'), 'report_def', ['tenant_id'], unique=False)
    op.add_column('invoice_line', sa.Column('kind', sa.String(length=20), server_default='charge', nullable=False))
    op.add_column('subscription', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_subscription_product_id'), 'subscription', ['product_id'], unique=False)
    op.create_foreign_key(None, 'subscription', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###

    # RLS: new tenant tables created after the enable-RLS migration → same NULLIF-guarded policy.
    for table in ("product", "report_def"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid)
              WITH CHECK (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("product", "report_def"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_product_id'), table_name='subscription')
    op.drop_column('subscription', 'product_id')
    op.drop_column('invoice_line', 'kind')
    op.drop_index(op.f('ix_report_def_tenant_id'), table_name='report_def')
    op.drop_index(op.f('ix_report_def_owner_user_id'), table_name='report_def')
    op.drop_table('report_def')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
