"""api_key + perf indexes

Revision ID: 7f342faffc15
Revises: b1c768523e3e
Create Date: 2026-05-26 16:13:31.540865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f342faffc15'
down_revision: Union[str, Sequence[str], None] = 'b1c768523e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('acts_as_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acts_as_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_key_prefix'), 'api_key', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_key_tenant_id'), 'api_key', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # RLS for api_key (created after the enable-RLS migration).
    op.execute("ALTER TABLE api_key ENABLE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON api_key
          USING (tenant_id = NULLIF(current_setting('gaahex.tenant_id', true), '')::uuid)
          WITH CHECK (tenant_id = NULLIF(current_setting('gaahex.tenant_id', true), '')::uuid);
    """)

    # E13 perf indexes for the hot scans (list/feed/aggregation).
    op.create_index("ix_record_tenant_entity_created", "record", ["tenant_id", "entity_key", "created_at"], unique=False)
    op.create_index("ix_event_tenant_created", "event", ["tenant_id", "created_at"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_event_tenant_created", table_name="event")
    op.drop_index("ix_record_tenant_entity_created", table_name="record")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON api_key;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_tenant_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_prefix'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
