"""entity_def.order

Revision ID: 9e0d19317944
Revises: 143f1fdeb609
Create Date: 2026-05-26 09:49:37.485731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0d19317944'
down_revision: Union[str, Sequence[str], None] = '143f1fdeb609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; NOT NULL stays enforced afterward
    op.add_column('entity_def', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_def', 'order')
    # ### end Alembic commands ###
