"""tenant profile columns (currency, locale, logo_text, onboarded_at)

Revision ID: a95459b83902
Revises: 3aaf9ce9edeb
Create Date: 2026-05-27 01:30:52.655982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95459b83902'
down_revision: Union[str, Sequence[str], None] = '3aaf9ce9edeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (removed autogenerate's spurious drops of the E13 raw-SQL perf indexes — they must survive.)
    op.add_column('tenant', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column('tenant', sa.Column('locale', sa.String(length=8), nullable=True))
    op.add_column('tenant', sa.Column('logo_text', sa.String(length=40), nullable=True))
    op.add_column('tenant', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'onboarded_at')
    op.drop_column('tenant', 'logo_text')
    op.drop_column('tenant', 'locale')
    op.drop_column('tenant', 'currency')
    # ### end Alembic commands ###
