"""outbound + webhooks

Revision ID: b1c768523e3e
Revises: 18062d97ef59
Create Date: 2026-05-26 16:00:32.115100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c768523e3e'
down_revision: Union[str, Sequence[str], None] = '18062d97ef59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_def',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_def_tenant_id'), 'webhook_def', ['tenant_id'], unique=False)
    op.create_table('webhook_delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook_def.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_tenant_id'), 'webhook_delivery', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_webhook_id'), 'webhook_delivery', ['webhook_id'], unique=False)
    op.create_table('outbound_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('to_addr', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('def_key', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_message_tenant_id'), 'outbound_message', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in ("outbound_message", "webhook_def", "webhook_delivery"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid)
              WITH CHECK (tenant_id = NULLIF(current_setting('gaaex.tenant_id', true), '')::uuid);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("outbound_message", "webhook_def", "webhook_delivery"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_message_tenant_id'), table_name='outbound_message')
    op.drop_table('outbound_message')
    op.drop_index(op.f('ix_webhook_delivery_webhook_id'), table_name='webhook_delivery')
    op.drop_index(op.f('ix_webhook_delivery_tenant_id'), table_name='webhook_delivery')
    op.drop_table('webhook_delivery')
    op.drop_index(op.f('ix_webhook_def_tenant_id'), table_name='webhook_def')
    op.drop_table('webhook_def')
    # ### end Alembic commands ###
