"""translation table

Revision ID: d2a4f9ad44dd
Revises: 5dbf421773ca
Create Date: 2026-05-26 20:10:43.367059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a4f9ad44dd'
down_revision: Union[str, Sequence[str], None] = '5dbf421773ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lang', 'key', name='uq_translation_key')
    )
    op.create_index(op.f('ix_translation_tenant_id'), 'translation', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    # (removed autogenerate's spurious drops of the E13 perf indexes — they must survive.)

    # SPECIAL RLS for translation: GLOBAL rows (tenant_id NULL) are readable by every tenant (shared
    # default strings); a tenant can only WRITE its own overrides. Global rows are seeded by the OWNER
    # (which bypasses RLS), so WITH CHECK keying on tenant is fine.
    op.execute("ALTER TABLE translation ENABLE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON translation
          USING (tenant_id IS NULL OR tenant_id = NULLIF(current_setting('gaahex.tenant_id', true), '')::uuid)
          WITH CHECK (tenant_id = NULLIF(current_setting('gaahex.tenant_id', true), '')::uuid);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON translation;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_tenant_id'), table_name='translation')
    op.drop_table('translation')
    # ### end Alembic commands ###
