"""Server-rendered HTML label translations (T-P4-3).

FastAPI renders branded HTML for invoices, receipts, and statements. Those
docs ship customer-facing strings ("Invoice", "Period", "Balance due", …).
Pre-T-P4-3 every label was hardcoded English; Armenian customers received
English documents.

This module bundles the label dict for the three customer-facing locales
(en / hy / ru) and exposes:
* `pick_locale(accept_language)` — pick a locale from an HTTP `Accept-Language`
  header (or fall back to `en`).
* `t(key, locale, fallback=None)` — synchronous lookup. Misses fall back to
  the English value, or to the explicit `fallback`, or to the key itself.

No DB hit on the render path. The translation table in `routers/i18n.py`
remains the authoritative source for *runtime-tenant-overridable* labels
(admin SPA + studio); HTML rendering uses these bundled values for speed
and decoupling from the admin tenant config.
"""
from __future__ import annotations

from typing import Iterable, Literal

Locale = Literal["en", "hy", "ru"]
SUPPORTED: tuple[Locale, ...] = ("en", "hy", "ru")
DEFAULT_LOCALE: Locale = "en"


# Invoice / receipt / statement labels.
INVOICE_LABELS: dict[str, dict[Locale, str]] = {
    "invoice":      {"en": "Invoice",        "hy": "Ապրանքագիր",    "ru": "Счёт"},
    "receipt":      {"en": "Receipt",        "hy": "Անդորրագիր",     "ru": "Квитанция"},
    "statement":    {"en": "Statement",      "hy": "Քաղվածք",         "ru": "Выписка"},
    "issuer":       {"en": "Invoice issuer", "hy": "Թողարկող",        "ru": "Эмитент"},
    "billed_to":    {"en": "Billed to",      "hy": "Հաշիվ-ապրանքագիր ստացողը", "ru": "Получатель"},
    "customer":     {"en": "Customer",       "hy": "Հաճախորդ",        "ru": "Клиент"},
    "status":       {"en": "Status",         "hy": "Կարգավիճակ",      "ru": "Статус"},
    "period":       {"en": "Period",         "hy": "Ժամանակաշրջան",   "ru": "Период"},
    "issued":       {"en": "Issued",         "hy": "Թողարկված",       "ru": "Выдан"},
    "due":          {"en": "Due",            "hy": "Վերջնաժ.",        "ru": "Срок"},
    "issued_due":   {"en": "Issued / Due",   "hy": "Թողարկված / Վերջնաժ.", "ru": "Выдан / Срок"},
    "description":  {"en": "Description",    "hy": "Նկարագրություն",  "ru": "Описание"},
    "qty":          {"en": "Qty",            "hy": "Քանակ",           "ru": "Кол-во"},
    "unit_price":   {"en": "Unit price",     "hy": "Միավորի գին",     "ru": "Цена"},
    "unit":         {"en": "Unit",           "hy": "Միավոր",          "ru": "Ед."},
    "amount":       {"en": "Amount",         "hy": "Գումար",          "ru": "Сумма"},
    "total":        {"en": "Total",          "hy": "Ընդամենը",        "ru": "Итого"},
    "paid":         {"en": "Paid",           "hy": "Վճարված",         "ru": "Оплачено"},
    "balance_due":  {"en": "Balance due",    "hy": "Մնացորդ",          "ru": "Остаток"},
    "payments":     {"en": "Payments",       "hy": "Վճարումներ",       "ru": "Платежи"},
    "date":         {"en": "Date",           "hy": "Ամսաթիվ",         "ru": "Дата"},
    "method":       {"en": "Method",         "hy": "Եղանակ",          "ru": "Способ"},
    "no_lines":     {"en": "No line items.", "hy": "Տողեր չկան։",     "ru": "Нет позиций."},
    "footer":       {"en": "Generated by",   "hy": "Թողարկված է",     "ru": "Сформировано"},
    "amounts_in":   {"en": "All amounts in Armenian Dram (֏).", "hy": "Բոլոր գումարները հայկական դրամով են (֏)։", "ru": "Все суммы в армянских драмах (֏)."},
    "computer_generated_receipt": {"en": "This is a computer-generated receipt.", "hy": "Սա համակարգչային եղանակով գեներացված անդորրագիր է։", "ru": "Это автоматически сформированная квитанция."},
    "payment_receipt": {"en": "Payment Receipt", "hy": "Վճարման անդորրագիր", "ru": "Квитанция об оплате"},
    # Status pill labels
    "status.DRAFT":   {"en": "DRAFT",   "hy": "ՍԵՎԱԳԻՐ",    "ru": "ЧЕРНОВИК"},
    "status.ISSUED":  {"en": "ISSUED",  "hy": "ԹՈՂԱՐԿՎԱԾ",  "ru": "ВЫДАН"},
    "status.PAID":    {"en": "PAID",    "hy": "ՎՃԱՐՎԱԾ",    "ru": "ОПЛАЧЕНО"},
    "status.OVERDUE": {"en": "OVERDUE", "hy": "ԺԱՄԿ. ԱՆՑԱԾ", "ru": "ПРОСРОЧЕН"},
    "status.VOID":    {"en": "VOID",    "hy": "ՉԵՂՅԱԼ",      "ru": "АННУЛИРОВАН"},
}


def _parse_priority(token: str) -> tuple[float, str]:
    """Parse `'hy;q=0.9'` → `(0.9, 'hy')`. Missing q defaults to 1.0."""
    parts = token.strip().split(";")
    locale = parts[0].strip().lower().split("-")[0]  # 'hy-AM' → 'hy'
    q = 1.0
    for p in parts[1:]:
        kv = p.strip().split("=", 1)
        if len(kv) == 2 and kv[0].strip().lower() == "q":
            try:
                q = float(kv[1].strip())
            except ValueError:
                pass
    return q, locale


def pick_locale(accept_language: str | None) -> Locale:
    """Pick the best-supported locale from an `Accept-Language` header.

    Examples::

        pick_locale("hy-AM,hy;q=0.9,en;q=0.7") -> "hy"
        pick_locale("ru;q=0.8,en;q=0.5")        -> "ru"
        pick_locale(None)                        -> "en"
        pick_locale("fr-FR")                     -> "en"  (unsupported → fallback)
    """
    if not accept_language:
        return DEFAULT_LOCALE
    candidates: list[tuple[float, str]] = []
    for token in accept_language.split(","):
        if not token.strip():
            continue
        candidates.append(_parse_priority(token))
    candidates.sort(key=lambda x: -x[0])  # highest q first
    for _, locale in candidates:
        if locale in SUPPORTED:
            return locale  # type: ignore[return-value]
    return DEFAULT_LOCALE


def t(key: str, locale: Locale = DEFAULT_LOCALE, fallback: str | None = None) -> str:
    """Look up a label by `key` for `locale`.

    Order: `INVOICE_LABELS[key][locale]` → `INVOICE_LABELS[key]['en']` →
    `fallback` → `key`. The English fallback ensures unsupported languages or
    missing translations still render readable text.
    """
    entry = INVOICE_LABELS.get(key)
    if entry is None:
        return fallback if fallback is not None else key
    return entry.get(locale) or entry.get("en") or (fallback if fallback is not None else key)


def locales() -> Iterable[Locale]:
    return SUPPORTED
