// GAAhex emoji pack — the curated set for COMMUNICATION features only (Messenger / chat, email,
// comments — any message a user types and sends). Per BRAND.md §4, emoji are allowed in user-authored
// message content; the product UI/iconography stays SVG (see icons.tsx). This is the emoji picker's
// source set, grouped into the 9 standard categories. Each entry is "<emoji> <name>".

export type EmojiCategory = { name: string; items: string[] }

/** Split an entry like "😀 grinning" into its char + name. */
export function parseEmoji(entry: string): { char: string; name: string } {
  const i = entry.indexOf(' ')
  return i < 0 ? { char: entry, name: '' } : { char: entry.slice(0, i), name: entry.slice(i + 1) }
}

export const EMOJI_PACK: EmojiCategory[] = [
  {
    name: 'Smileys & Emotion',
    items: [
      '😀 grinning', '😃 smiley', '😄 happy', '😁 beaming', '😆 laugh', '😅 sweat smile', '🤣 rofl',
      '😂 joy', '🙂 slight smile', '🙃 upside down', '😉 wink', '😊 blush', '😇 innocent', '🥰 loved',
      '😍 heart eyes', '🤩 star struck', '😘 kiss', '😗 kissing', '😚 kiss closed', '😙 kiss smile',
      '🥲 happy tear', '😋 yum', '😛 tongue', '😜 wink tongue', '🤪 zany', '😝 squint tongue',
      '🤑 money mouth', '🤗 hug', '🤭 oops', '🤫 shush', '🤔 thinking', '🤐 zipped', '🤨 raised brow',
      '😐 neutral', '😑 expressionless', '😶 speechless', '😶‍🌫️ in clouds', '😏 smirk', '😒 unamused',
      '🙄 eye roll', '😬 grimace', '😮‍💨 exhale', '🤥 lying', '😌 relieved', '😔 pensive', '😪 sleepy',
      '🤤 drool', '😴 sleep', '😷 mask', '🤒 sick', '🤕 injured', '🤢 nausea', '🤮 vomit', '🤧 sneeze',
      '🥵 hot', '🥶 cold', '🥴 woozy', '😵 dizzy', '😵‍💫 spiral', '🤯 mind blown', '🤠 cowboy', '🥳 party',
      '🥸 disguise', '😎 cool', '🤓 nerd', '🧐 monocle', '😕 confused', '😟 worried', '🙁 frown',
      '☹️ sad', '😮 surprised', '😯 hushed', '😲 astonished', '😳 flushed', '🥺 pleading',
      '🥹 holding tears', '😦 anguished', '😧 anxious', '😨 fearful', '😰 cold sweat', '😥 sad sweat',
      '😢 cry', '😭 sob', '😱 scream', '😖 confounded', '😣 persevere', '😞 disappointed', '😓 sweat',
      '😩 weary', '😫 tired', '🥱 yawn', '😤 huff', '😡 angry', '😠 mad', '🤬 cursing', '😈 smiling devil',
      '👿 angry devil', '💀 skull', '☠️ skull bones', '💩 poop', '🤡 clown', '👹 ogre', '👺 goblin',
      '👻 ghost', '👽 alien', '👾 alien monster', '🤖 robot', '😺 cat smile', '😸 cat grin', '😹 cat joy',
      '😻 cat love', '😼 cat smirk', '😽 cat kiss', '🙀 cat shock', '😿 cat cry', '😾 cat pout',
      '🙈 see no', '🙉 hear no', '🙊 speak no', '💋 kiss mark', '💘 heart arrow', '💝 heart gift',
      '💖 sparkle heart', '💗 growing heart', '💓 beating heart', '💞 revolving heart', '💕 two hearts',
      '💟 heart deco', '❣️ heart exclaim', '💔 broken heart', '❤️‍🔥 heart fire', '❤️‍🩹 mending heart',
      '❤️ red heart', '🧡 orange heart', '💛 yellow heart', '💚 green heart', '💙 blue heart',
      '💜 purple heart', '🤎 brown heart', '🖤 black heart', '🤍 white heart', '💯 hundred', '💢 anger',
      '💥 boom', '💫 dizzy', '💦 sweat drops', '💨 dash', '🕳️ hole', '💣 bomb', '💬 speech',
      '👁️‍🗨️ eye speech', '🗨️ left speech', '🗯️ anger speech', '💭 thought', '💤 zzz',
    ],
  },
  {
    name: 'People & Body',
    items: [
      '👋 wave', '🤚 raised back', '🖐️ raised hand', '✋ stop', '🖖 vulcan', '👌 ok hand', '🤌 pinched',
      '🤏 pinch', '✌️ peace', '🤞 fingers crossed', '🫰 finger heart', '🤟 love you', '🤘 rock',
      '🤙 call me', '👈 left', '👉 right', '👆 up', '🖕 middle finger', '👇 down', '☝️ index up', '🫵 you',
      '👍 thumbs up', '👎 thumbs down', '✊ raised fist', '👊 fist', '🤛 left fist', '🤜 right fist',
      '👏 clap', '🙌 raised hands', '🫶 heart hands', '👐 open hands', '🤲 palms up', '🤝 handshake',
      '🙏 pray', '✍️ writing', '💅 nails', '🤳 selfie', '💪 muscle', '🦾 robotic arm',
      '🦿 mechanical leg', '🦵 leg', '🦶 foot', '👂 ear', '🦻 hearing aid', '👃 nose', '🧠 brain',
      '🫀 heart organ', '🫁 lungs', '🦷 tooth', '🦴 bone', '👀 eyes', '👁️ eye', '👅 tongue', '👄 mouth',
      '🫦 biting lip', '👶 baby', '🧒 child', '👦 boy', '👧 girl', '🧑 person', '👨 man', '👩 woman',
      '🧓 older person', '👴 old man', '👵 old woman', '🙅 no gesture', '🙆 ok gesture', '💁 info desk',
      '🙋 raising hand', '🧏 deaf person', '🙇 bowing', '🤦 facepalm', '🤷 shrug', '🧑‍⚕️ health worker',
      '🧑‍🎓 student', '🧑‍🏫 teacher', '🧑‍⚖️ judge', '🧑‍🌾 farmer', '🧑‍🍳 cook', '🧑‍🔧 mechanic',
      '🧑‍🏭 factory worker', '🧑‍💼 office worker', '🧑‍🔬 scientist', '🧑‍💻 technologist', '🧑‍🎤 singer',
      '🧑‍🎨 artist', '🧑‍✈️ pilot', '🧑‍🚀 astronaut', '🧑‍🚒 firefighter', '👮 police', '🕵️ detective',
      '💂 guard', '🥷 ninja', '👷 construction', '🤴 prince', '👸 princess', '👰 person veil',
      '🤵 person tuxedo', '👼 baby angel', '🎅 santa', '🤶 mrs claus', '🦸 superhero', '🦹 supervillain',
      '🧙 mage', '🧚 fairy', '🧛 vampire', '🧜 merperson', '🧝 elf', '🧞 genie', '🧟 zombie',
      '💆 massage', '💇 haircut', '🚶 walking', '🧍 standing', '🧎 kneeling', '🏃 running',
      '💃 dancing woman', '🕺 dancing man', '🕴️ levitating', '👯 dancers', '🧖 sauna', '🧗 climbing',
      '🤺 fencing', '🏇 horse racing', '⛷️ skier', '🏂 snowboarder', '🏌️ golf', '🏄 surfing',
      '🚣 rowing', '🏊 swimming', '⛹️ bouncing ball', '🏋️ lifting', '🚴 cycling', '🚵 mountain bike',
      '🤸 cartwheel', '🤼 wrestling', '🤽 water polo', '🤾 handball', '🤹 juggling', '🧘 meditation',
      '🛀 bath', '🛌 sleeping bed', '👭 holding hands ww', '👫 holding hands wm', '👬 holding hands mm',
      '💏 kiss couple', '💑 couple heart', '👪 family', '🗣️ speaking head', '👤 silhouette',
      '👥 silhouettes', '🫂 people hugging', '👣 footprints',
    ],
  },
  {
    name: 'Animals & Nature',
    items: [
      '🐵 monkey face', '🐒 monkey', '🦍 gorilla', '🦧 orangutan', '🐶 dog face', '🐕 dog',
      '🦮 guide dog', '🐩 poodle', '🐺 wolf', '🦊 fox', '🦝 raccoon', '🐱 cat face', '🐈 cat',
      '🐈‍⬛ black cat', '🦁 lion', '🐯 tiger face', '🐅 tiger', '🐆 leopard', '🐴 horse face', '🐎 horse',
      '🦄 unicorn', '🦓 zebra', '🦌 deer', '🦬 bison', '🐮 cow face', '🐂 ox', '🐃 water buffalo',
      '🐄 cow', '🐷 pig face', '🐖 pig', '🐗 boar', '🐽 pig nose', '🐏 ram', '🐑 ewe', '🐐 goat',
      '🐪 camel', '🐫 two hump camel', '🦙 llama', '🦒 giraffe', '🐘 elephant', '🦣 mammoth', '🦏 rhino',
      '🦛 hippo', '🐭 mouse face', '🐁 mouse', '🐀 rat', '🐹 hamster', '🐰 rabbit face', '🐇 rabbit',
      '🐿️ chipmunk', '🦫 beaver', '🦔 hedgehog', '🦇 bat', '🐻 bear', '🐻‍❄️ polar bear', '🐨 koala',
      '🐼 panda', '🦥 sloth', '🦦 otter', '🦨 skunk', '🦘 kangaroo', '🦡 badger', '🐾 paw prints',
      '🦃 turkey', '🐔 chicken', '🐓 rooster', '🐣 hatching', '🐤 baby chick', '🐥 front chick',
      '🐦 bird', '🐧 penguin', '🕊️ dove', '🦅 eagle', '🦆 duck', '🦢 swan', '🦉 owl', '🦤 dodo',
      '🪶 feather', '🦩 flamingo', '🦚 peacock', '🦜 parrot', '🐸 frog', '🐊 crocodile', '🐢 turtle',
      '🦎 lizard', '🐍 snake', '🐲 dragon face', '🐉 dragon', '🦕 sauropod', '🦖 t rex',
      '🐳 spouting whale', '🐋 whale', '🐬 dolphin', '🦭 seal', '🐟 fish', '🐠 tropical fish',
      '🐡 blowfish', '🦈 shark', '🐙 octopus', '🐚 shell', '🪸 coral', '🐌 snail', '🦋 butterfly',
      '🐛 bug', '🐜 ant', '🐝 bee', '🪲 beetle', '🐞 lady beetle', '🦗 cricket', '🪳 cockroach',
      '🕷️ spider', '🕸️ web', '🦂 scorpion', '🦟 mosquito', '🪰 fly', '🪱 worm', '🦠 microbe',
      '💐 bouquet', '🌸 cherry blossom', '💮 white flower', '🪷 lotus', '🏵️ rosette', '🌹 rose',
      '🥀 wilted', '🌺 hibiscus', '🌻 sunflower', '🌼 blossom', '🌷 tulip', '🌱 seedling',
      '🪴 potted plant', '🌲 evergreen', '🌳 tree', '🌴 palm tree', '🌵 cactus', '🌾 sheaf', '🌿 herb',
      '☘️ shamrock', '🍀 four leaf', '🍁 maple leaf', '🍂 fallen leaf', '🍃 leaf wind',
    ],
  },
  {
    name: 'Food & Drink',
    items: [
      '🍇 grapes', '🍈 melon', '🍉 watermelon', '🍊 tangerine', '🍋 lemon', '🍌 banana', '🍍 pineapple',
      '🥭 mango', '🍎 red apple', '🍏 green apple', '🍐 pear', '🍑 peach', '🍒 cherries', '🍓 strawberry',
      '🫐 blueberries', '🥝 kiwi', '🍅 tomato', '🫒 olive', '🥥 coconut', '🥑 avocado', '🍆 eggplant',
      '🥔 potato', '🥕 carrot', '🌽 corn', '🌶️ hot pepper', '🫑 bell pepper', '🥒 cucumber',
      '🥬 leafy green', '🥦 broccoli', '🧄 garlic', '🧅 onion', '🍄 mushroom', '🥜 peanuts',
      '🌰 chestnut', '🍞 bread', '🥐 croissant', '🥖 baguette', '🫓 flatbread', '🥨 pretzel', '🥯 bagel',
      '🥞 pancakes', '🧇 waffle', '🧀 cheese', '🍖 meat bone', '🍗 poultry leg', '🥩 cut of meat',
      '🥓 bacon', '🍔 burger', '🍟 fries', '🍕 pizza', '🌭 hot dog', '🥪 sandwich', '🌮 taco',
      '🌯 burrito', '🫔 tamale', '🥙 stuffed flatbread', '🧆 falafel', '🥚 egg', '🍳 cooking',
      '🥘 shallow pan', '🍲 pot of food', '🫕 fondue', '🥣 bowl spoon', '🥗 salad', '🍿 popcorn',
      '🧈 butter', '🧂 salt', '🥫 canned', '🍱 bento', '🍘 rice cracker', '🍙 rice ball',
      '🍚 cooked rice', '🍛 curry', '🍜 ramen', '🍝 spaghetti', '🍠 roasted sweet potato', '🍢 oden',
      '🍣 sushi', '🍤 fried shrimp', '🍥 fish cake', '🥮 moon cake', '🍡 dango', '🥟 dumpling',
      '🥠 fortune cookie', '🥡 takeout', '🦀 crab', '🦞 lobster', '🦐 shrimp', '🦑 squid', '🦪 oyster',
      '🍦 soft serve', '🍧 shaved ice', '🍨 ice cream', '🍩 doughnut', '🍪 cookie', '🎂 birthday cake',
      '🍰 shortcake', '🧁 cupcake', '🥧 pie', '🍫 chocolate', '🍬 candy', '🍭 lollipop', '🍮 custard',
      '🍯 honey pot', '🍼 baby bottle', '🥛 milk', '☕ coffee', '🫖 teapot', '🍵 tea', '🍶 sake',
      '🍾 champagne', '🍷 wine', '🍸 cocktail', '🍹 tropical drink', '🍺 beer', '🍻 clinking beers',
      '🥂 clinking glasses', '🥃 tumbler', '🥤 cup straw', '🧋 bubble tea', '🧃 juice box', '🧉 mate',
      '🧊 ice', '🥢 chopsticks', '🍽️ plate', '🍴 fork knife', '🥄 spoon', '🔪 knife', '🫙 jar',
      '🏺 amphora',
    ],
  },
  {
    name: 'Travel & Places',
    items: [
      '🌍 earth africa', '🌎 earth americas', '🌏 earth asia', '🌐 globe meridians', '🗺️ world map',
      '🗾 japan', '🧭 compass', '🏔️ snow mountain', '⛰️ mountain', '🌋 volcano', '🗻 fuji',
      '🏕️ camping', '🏖️ beach', '🏜️ desert', '🏝️ desert island', '🏞️ park', '🏟️ stadium',
      '🏛️ classical building', '🏗️ construction', '🧱 brick', '🪨 rock', '🪵 wood', '🛖 hut',
      '🏘️ houses', '🏚️ derelict', '🏠 house', '🏡 house garden', '🏢 office', '🏣 jp post',
      '🏤 post office', '🏥 hospital', '🏦 bank', '🏨 hotel', '🏩 love hotel', '🏪 convenience',
      '🏫 school', '🏬 department store', '🏭 factory', '🏯 jp castle', '🏰 castle', '💒 wedding',
      '🗼 tokyo tower', '🗽 statue of liberty', '⛪ church', '🕌 mosque', '🛕 hindu temple',
      '🕍 synagogue', '⛩️ shinto shrine', '🕋 kaaba', '⛲ fountain', '⛺ tent', '🌁 foggy',
      '🌃 night stars', '🏙️ cityscape', '🌄 sunrise mountain', '🌅 sunrise', '🌆 city dusk',
      '🌇 sunset', '🌉 bridge night', '♨️ hot springs', '🎠 carousel', '🛝 playground',
      '🎡 ferris wheel', '🎢 roller coaster', '💈 barber pole', '🎪 circus', '🚂 locomotive',
      '🚃 railway car', '🚄 high speed', '🚅 bullet train', '🚆 train', '🚇 metro', '🚈 light rail',
      '🚉 station', '🚊 tram', '🚝 monorail', '🚞 mountain railway', '🚋 tram car', '🚌 bus',
      '🚍 oncoming bus', '🚎 trolleybus', '🚐 minibus', '🚑 ambulance', '🚒 fire engine',
      '🚓 police car', '🚔 oncoming police', '🚕 taxi', '🚖 oncoming taxi', '🚗 car', '🚘 oncoming car',
      '🚙 suv', '🛻 pickup', '🚚 truck', '🚛 articulated truck', '🚜 tractor', '🏎️ racing car',
      '🏍️ motorcycle', '🛵 motor scooter', '🦽 manual wheelchair', '🦼 motor wheelchair',
      '🛺 auto rickshaw', '🚲 bicycle', '🛴 scooter', '🛹 skateboard', '🛼 roller skate', '🚏 bus stop',
      '🛣️ motorway', '🛤️ railway track', '🛢️ oil drum', '⛽ fuel pump', '🛞 wheel', '🚨 police light',
      '🚥 horizontal light', '🚦 vertical light', '🛑 stop sign', '🚧 construction sign', '⚓ anchor',
      '🛟 ring buoy', '⛵ sailboat', '🛶 canoe', '🚤 speedboat', '🛳️ passenger ship', '⛴️ ferry',
      '🛥️ motor boat', '🚢 ship', '✈️ airplane', '🛩️ small airplane', '🛫 takeoff', '🛬 landing',
      '🪂 parachute', '💺 seat', '🚁 helicopter', '🚟 suspension railway', '🚠 mountain cableway',
      '🚡 aerial tramway', '🛰️ satellite', '🚀 rocket', '🛸 ufo', '🛎️ bellhop bell', '🧳 luggage',
      '⌛ hourglass done', '⏳ hourglass flow', '⌚ watch', '⏰ alarm clock', '⏱️ stopwatch', '⏲️ timer',
      '🕰️ mantelpiece clock', '🕛 12', '🕧 12 30', '🕐 1', '🕜 1 30', '🕑 2', '🕝 2 30', '🕒 3',
      '🕞 3 30', '🕓 4', '🕟 4 30', '🕔 5', '🕠 5 30', '🕕 6', '🕡 6 30', '🕖 7', '🕢 7 30', '🕗 8',
      '🕣 8 30', '🕘 9', '🕤 9 30', '🕙 10', '🕥 10 30', '🕚 11', '🕦 11 30', '🌑 new moon',
      '🌒 waxing crescent', '🌓 first quarter', '🌔 waxing gibbous', '🌕 full moon', '🌖 waning gibbous',
      '🌗 last quarter', '🌘 waning crescent', '🌙 crescent', '🌚 new moon face', '🌛 first quarter face',
      '🌜 last quarter face', '🌡️ thermometer', '☀️ sun', '🌝 full moon face', '🌞 sun face',
      '🪐 ringed planet', '⭐ star', '🌟 glowing star', '🌠 shooting star', '🌌 milky way', '☁️ cloud',
      '⛅ sun cloud', '⛈️ cloud lightning rain', '🌤️ sun small cloud', '🌥️ sun large cloud',
      '🌦️ sun rain', '🌧️ cloud rain', '🌨️ cloud snow', '🌩️ cloud lightning', '🌪️ tornado', '🌫️ fog',
      '🌬️ wind face', '🌀 cyclone', '🌈 rainbow', '🌂 closed umbrella', '☂️ umbrella', '☔ umbrella rain',
      '⛱️ umbrella ground', '⚡ lightning', '❄️ snowflake', '☃️ snowman snow', '⛄ snowman', '☄️ comet',
    ],
  },
  {
    name: 'Activities',
    items: [
      '🎃 jack o lantern', '🎄 christmas tree', '🎆 fireworks', '🎇 sparkler', '🧨 firecracker',
      '✨ sparkles', '🎈 balloon', '🎉 party popper', '🎊 confetti', '🎋 tanabata tree',
      '🎍 pine decoration', '🎎 jp dolls', '🎏 carp streamer', '🎐 wind chime', '🎑 moon ceremony',
      '🧧 red envelope', '🎀 ribbon', '🎁 gift', '🎗️ reminder ribbon', '🎟️ admission tickets',
      '🎫 ticket', '🎖️ military medal', '🏆 trophy', '🏅 sports medal', '🥇 gold', '🥈 silver',
      '🥉 bronze', '⚽ soccer', '⚾ baseball', '🥎 softball', '🏀 basketball', '🏐 volleyball',
      '🏈 american football', '🏉 rugby', '🎾 tennis', '🥏 flying disc', '🎳 bowling', '🏏 cricket bat',
      '🏑 field hockey', '🏒 ice hockey', '🥍 lacrosse', '🏓 ping pong', '🏸 badminton',
      '🥊 boxing glove', '🥋 martial arts', '🥅 goal net', '⛳ flag in hole', '⛸️ ice skate',
      '🎣 fishing', '🤿 diving mask', '🎽 running shirt', '🎿 skis', '🛷 sled', '🥌 curling',
      '🎯 bullseye', '🪀 yo yo', '🪁 kite', '🔫 toy gun', '🎱 8 ball', '🔮 crystal ball', '🪄 magic wand',
      '🎮 video game', '🕹️ joystick', '🎰 slot machine', '🎲 die', '🧩 puzzle piece', '🧸 teddy bear',
      '🪅 pinata', '🪆 nesting dolls', '♠️ spade', '♥️ heart suit', '♦️ diamond suit', '♣️ club',
      '♟️ chess pawn', '🃏 joker', '🀄 mahjong', '🎴 flower cards', '🎭 performing arts',
      '🖼️ framed picture', '🎨 art palette', '🧵 thread', '🪡 sewing needle', '🧶 yarn', '🪢 knot',
    ],
  },
  {
    name: 'Objects',
    items: [
      '👓 glasses', '🕶️ sunglasses', '🥽 goggles', '🥼 lab coat', '🦺 safety vest', '👔 necktie',
      '👕 shirt', '👖 jeans', '🧣 scarf', '🧤 gloves', '🧥 coat', '🧦 socks', '👗 dress', '👘 kimono',
      '🥻 sari', '🩱 one piece', '🩲 briefs', '🩳 shorts', '👙 bikini', '👚 blouse', '👛 purse',
      '👜 handbag', '👝 clutch', '🛍️ shopping bags', '🎒 backpack', '🩴 sandal', '👞 mans shoe',
      '👟 running shoe', '🥾 hiking boot', '🥿 flat shoe', '👠 high heel', '👡 womans sandal',
      '🩰 ballet shoes', '👢 womans boot', '👑 crown', '👒 womans hat', '🎩 top hat', '🎓 graduation cap',
      '🧢 billed cap', '🪖 helmet', '⛑️ rescue helmet', '📿 prayer beads', '💄 lipstick', '💍 ring',
      '💎 gem', '🔇 muted speaker', '🔈 low speaker', '🔉 medium speaker', '🔊 loud speaker',
      '📢 loudspeaker', '📣 megaphone', '📯 postal horn', '🔔 bell', '🔕 bell slash', '🎼 musical score',
      '🎵 musical note', '🎶 musical notes', '🎙️ studio mic', '🎚️ level slider', '🎛️ control knobs',
      '🎤 microphone', '🎧 headphone', '📻 radio', '🎷 saxophone', '🪗 accordion', '🎸 guitar',
      '🎹 piano', '🎺 trumpet', '🎻 violin', '🪕 banjo', '🥁 drum', '🪘 long drum', '📱 phone',
      '📲 phone arrow', '☎️ telephone', '📞 receiver', '📟 pager', '📠 fax', '🔋 battery',
      '🪫 low battery', '🔌 plug', '💻 laptop', '🖥️ desktop', '🖨️ printer', '⌨️ keyboard', '🖱️ mouse',
      '🖲️ trackball', '💽 minidisc', '💾 floppy', '💿 cd', '📀 dvd', '🧮 abacus', '🎥 movie camera',
      '🎞️ film frames', '📽️ projector', '🎬 clapper', '📺 tv', '📷 camera', '📸 camera flash',
      '📹 video camera', '📼 videocassette', '🔍 magnifier left', '🔎 magnifier right', '🕯️ candle',
      '💡 light bulb', '🔦 flashlight', '🏮 lantern', '🪔 diya', '📔 decorated book', '📕 closed book',
      '📖 open book', '📗 green book', '📘 blue book', '📙 orange book', '📚 books', '📓 notebook',
      '📒 ledger', '📃 page curl', '📜 scroll', '📄 page', '📰 newspaper', '🗞️ rolled newspaper',
      '📑 bookmark tabs', '🔖 bookmark', '🏷️ tag', '💰 money bag', '🪙 coin', '💴 yen', '💵 dollar',
      '💶 euro', '💷 pound', '💸 money wings', '💳 credit card', '🧾 receipt', '💹 chart up yen',
      '✉️ envelope', '📧 email', '📨 incoming', '📩 envelope arrow', '📤 outbox', '📥 inbox',
      '📦 package', '📫 mailbox flag', '📪 mailbox no flag', '📬 open mailbox flag', '📭 open mailbox',
      '📮 postbox', '🗳️ ballot', '✏️ pencil', '✒️ black nib', '🖋️ fountain pen', '🖊️ pen',
      '🖌️ paintbrush', '🖍️ crayon', '📝 memo', '💼 briefcase', '📁 folder', '📂 open folder',
      '🗂️ card index dividers', '📅 calendar', '📆 tear off calendar', '🗒️ spiral notepad',
      '🗓️ spiral calendar', '📇 card index', '📈 chart up', '📉 chart down', '📊 bar chart',
      '📋 clipboard', '📌 pushpin', '📍 round pushpin', '📎 paperclip', '🖇️ linked paperclips',
      '📏 ruler', '📐 triangular ruler', '✂️ scissors', '🗃️ card file box', '🗄️ file cabinet',
      '🗑️ wastebasket', '🔒 locked', '🔓 unlocked', '🔏 lock pen', '🔐 lock key', '🔑 key',
      '🗝️ old key', '🔨 hammer', '🪓 axe', '⛏️ pick', '⚒️ hammer pick', '🛠️ tools', '🗡️ dagger',
      '⚔️ crossed swords', '💣 bomb', '🪃 boomerang', '🏹 bow arrow', '🛡️ shield', '🪚 carpentry saw',
      '🔧 wrench', '🪛 screwdriver', '🔩 nut bolt', '⚙️ gear', '🗜️ clamp', '⚖️ scales', '🦯 white cane',
      '🔗 link', '⛓️ chains', '🪝 hook', '🧰 toolbox', '🧲 magnet', '🪜 ladder', '⚗️ alembic',
      '🧪 test tube', '🧫 petri dish', '🧬 dna', '🔬 microscope', '🔭 telescope', '📡 satellite antenna',
      '💉 syringe', '🩸 blood drop', '💊 pill', '🩹 bandage', '🩺 stethoscope', '🩻 x ray', '🚪 door',
      '🛗 elevator', '🪞 mirror', '🪟 window', '🛏️ bed', '🛋️ couch lamp', '🪑 chair', '🚽 toilet',
      '🪠 plunger', '🚿 shower', '🛁 bathtub', '🪤 mouse trap', '🪒 razor', '🧴 lotion bottle',
      '🧷 safety pin', '🧹 broom', '🧺 basket', '🧻 roll of paper', '🪣 bucket', '🧼 soap', '🫧 bubbles',
      '🪥 toothbrush', '🧽 sponge', '🧯 fire extinguisher', '🛒 cart', '🚬 cigarette', '⚰️ coffin',
      '🪦 headstone', '⚱️ funeral urn', '🗿 moai', '🪧 placard', '🪪 id card',
    ],
  },
  {
    name: 'Symbols',
    items: [
      '🏧 atm', '🚮 litter bin', '🚰 potable water', '♿ wheelchair access', '🚹 mens', '🚺 womens',
      '🚻 restroom', '🚼 baby symbol', '🚾 wc', '🛂 passport control', '🛃 customs', '🛄 baggage claim',
      '🛅 left luggage', '⚠️ warning', '🚸 children crossing', '⛔ no entry', '🚫 prohibited',
      '🚳 no bicycles', '🚭 no smoking', '🚯 no litter', '🚱 not potable', '🚷 no pedestrians',
      '📵 no phones', '🔞 18', '☢️ radioactive', '☣️ biohazard', '⬆️ up arrow', '↗️ up right arrow',
      '➡️ right arrow', '↘️ down right arrow', '⬇️ down arrow', '↙️ down left arrow', '⬅️ left arrow',
      '↖️ up left arrow', '↕️ up down arrow', '↔️ left right arrow', '↩️ right hook', '↪️ left hook',
      '⤴️ up curve', '⤵️ down curve', '🔃 clockwise vertical', '🔄 counterclockwise', '🔙 back',
      '🔚 end', '🔛 on', '🔜 soon', '🔝 top', '🛐 worship place', '⚛️ atom', '🕉️ om',
      '✡️ star of david', '☸️ wheel dharma', '☯️ yin yang', '✝️ latin cross', '☦️ orthodox cross',
      '☪️ star crescent', '☮️ peace', '🕎 menorah', '🔯 six pointed star', '♈ aries', '♉ taurus',
      '♊ gemini', '♋ cancer', '♌ leo', '♍ virgo', '♎ libra', '♏ scorpio', '♐ sagittarius',
      '♑ capricorn', '♒ aquarius', '♓ pisces', '⛎ ophiuchus', '🔀 shuffle', '🔁 repeat',
      '🔂 repeat one', '▶️ play', '⏩ fast forward', '⏭️ next track', '⏯️ play pause', '◀️ reverse',
      '⏪ rewind', '⏮️ last track', '🔼 up button', '⏫ fast up', '🔽 down button', '⏬ fast down',
      '⏸️ pause', '⏹️ stop', '⏺️ record', '⏏️ eject', '🎦 cinema', '🔅 dim', '🔆 bright',
      '📶 signal bars', '📳 vibration', '📴 phone off', '♀️ female', '♂️ male', '⚧ transgender',
      '✖️ multiply', '➕ plus', '➖ minus', '➗ divide', '🟰 equals', '♾️ infinity',
      '‼️ double exclaim', '⁉️ exclaim question', '❓ red question', '❔ white question',
      '❕ white exclaim', '❗ red exclaim', '〰️ wavy dash', '💱 currency exchange', '💲 dollar sign',
      '⚕️ medical', '♻️ recycle', '⚜️ fleur de lis', '🔱 trident', '📛 name badge', '🔰 jp beginner',
      '⭕ hollow circle', '✅ check button', '☑️ check box', '✔️ check mark', '❌ cross mark',
      '❎ cross button', '➰ curly loop', '➿ double loop', '〽️ part alternation', '✳️ eight spoked',
      '✴️ eight pointed', '❇️ sparkle', '©️ copyright', '®️ registered', '™️ trademark', '#️⃣ hash',
      '*️⃣ asterisk', '0️⃣ zero', '1️⃣ one', '2️⃣ two', '3️⃣ three', '4️⃣ four', '5️⃣ five', '6️⃣ six',
      '7️⃣ seven', '8️⃣ eight', '9️⃣ nine', '🔟 ten', '🔠 abcd caps', '🔡 abcd lower', '🔢 1234',
      '🔣 symbols', '🔤 abc', '🅰️ a', '🆎 ab', '🅱️ b', '🆑 cl', '🆒 cool', '🆓 free', 'ℹ️ info',
      '🆔 id', 'Ⓜ️ m', '🆖 ng', '🅾️ o', '🆗 ok', '🅿️ p', '🆘 sos', '🆙 up', '🆚 vs', '🈁 here',
      '🈂️ service charge', '🉐 bargain', '🉑 accept', '㊙️ secret', '㊗️ congrats', '🈴 pass',
      '🈵 no vacancy', '🈹 discount', '🈲 prohibited jp', '🅰 a alt', '🈳 vacancy', '🈸 application',
      '🈺 open business', '🈷️ monthly', '🔴 red circle', '🟠 orange circle', '🟡 yellow circle',
      '🟢 green circle', '🔵 blue circle', '🟣 purple circle', '🟤 brown circle', '⚫ black circle',
      '⚪ white circle', '🟥 red square', '🟧 orange square', '🟨 yellow square', '🟩 green square',
      '🟦 blue square', '🟪 purple square', '🟫 brown square', '⬛ black square', '⬜ white square',
      '◼️ medium black', '◻️ medium white', '◾ small black', '◽ small white', '▪️ tiny black',
      '▫️ tiny white', '🔶 large orange diamond', '🔷 large blue diamond', '🔸 small orange diamond',
      '🔹 small blue diamond', '🔺 red triangle up', '🔻 red triangle down', '💠 diamond dot',
      '🔘 radio button', '🔳 white square button', '🔲 black square button',
    ],
  },
  {
    name: 'Flags',
    items: [
      '🏁 chequered flag', '🚩 triangular flag', '🎌 crossed flags', '🏴 black flag', '🏳️ white flag',
      '🏳️‍🌈 rainbow flag', '🏳️‍⚧️ trans flag', '🏴‍☠️ pirate flag',
    ],
  },
]
